Added the IssuerPermissions back to solve an bug
plugblockchain/plug-blockchain pull request #127
Opened 2020-08-26 21:41 UTC by royyang-centrality

Resolves the problem where issuers don't have access to send extrinsics to give self the permission to send extrinsics.
Added some unit tests back

2020-08-26 21:58 UTC, cowboy-bebug approved these changes
LGTM

2020-08-26 23:47 UTC, holygits requested changes
revoking part needs some reworking

2020-08-26 23:47 UTC, holygits commented on prml/consortium-permission/src/mock.rs
> +    /// Remove all self-claimed permissions from an issuer.
Not sure if comment wrong or implementation is wrong (maybe both)

/// Remove all self-claimed permissions from an issuer.
or
/// Remove self-claimed permission access permission for`issuer` (it does this afaict)

does it need the if block, since `ConsortiumPermission::claim((issuer, ACCESS_TOPIC.to_vec()));` would return `ACCESS_VALUE` false if it doesn't exist

2020-08-26 23:49 UTC, royyang-centrality commented on prml/consortium-permission/src/mock.rs
> +    /// Remove all self-claimed permissions from an issuer.
Roger. I'll update the comments and double check this

2020-08-26 23:51 UTC, holygits commented on prml/consortium-permission/src/lib.rs
> +            // Notify the revocation of all current permissions.
this comment doesn't line up with the implementation of `revoke_issuer_permissions`

2020-08-26 23:55 UTC, royyang-centrality commented on prml/consortium-permission/src/lib.rs
> +            // Notify the revocation of all current permissions.
revoke_issuer_permissions can behave differently depending on its implementation. 
the module will simply notify the revocation by calling the revoke_issuer_permissions on all the topics it is revoking

2020-08-26 23:56 UTC, holygits commented on prml/consortium-permission/src/lib.rs
> +            // Notify the revocation of all current permissions.
makes sense!

2020-08-26 23:57 UTC, royyang-centrality commented on prml/consortium-permission/src/mock.rs
> +    /// Remove all self-claimed permissions from an issuer.
I think the if block is needed. Because the "access" can be granted by another person. We should only revoke "access" if it is granted by the "issuer" themselves when "access" is revoked

2020-08-27 00:04 UTC, royyang-centrality commented on prml/consortium-permission/src/mock.rs
> +    /// Remove all self-claimed permissions from an issuer.
* Updated the comments here.

2020-08-27 00:10 UTC, holygits reviewed
looking good now
- mentioning self-claim is an important quirk imo
- missing one test for when `claim_issuer != issuer` (i.e. hit that if block)

2020-08-27 00:10 UTC, holygits commented on prml/consortium-permission/src/mock.rs
> +    /// "access" permission.
```suggestion
    /// When an issuer is authorized to make claims on the "access" topic, they also grant themselves
    /// "access" permission.
```

2020-08-27 00:10 UTC, holygits commented on prml/consortium-permission/src/mock.rs
> +    fn revoke_issuer_permissions(issuer: &Self::AccountId, topic: &Topic) {
```suggestion
    /// When an issuer's authority on the "access" topic is revoked, also revoke their self-claimed "access" permission.
```

2020-08-27 00:10 UTC, holygits commented on prml/consortium-permission/src/mock.rs
> +    /// Remove all self-claimed permissions from an issuer.
gotcha. I meant the outer if as this function seemed made to remove self access claim but now I see it _could_ be called by any topic

2020-08-27 00:12 UTC, holygits commented on prml/consortium-permission/src/mock.rs
> +    fn revoke_issuer_permissions(issuer: &Self::AccountId, topic: &Topic) {
don't commit this not sure if whitespace is correct 😅

2020-08-27 00:15 UTC, royyang-centrality commented on prml/consortium-permission/src/mock.rs
> +    /// Remove all self-claimed permissions from an issuer.
I want to make it so that we only revoke the "access" permission if when we revoke their authority on the "access" topic.
Because we could be revoking their rights on other topics, such as mint_burn, and others, but still want them to keep their "access" right. Otherwise revoking any authority will revoke their "access" right, which seems very harsh
does that make sense?

2020-08-27 00:40 UTC, royyang-centrality commented
> looking good now
> 
> * mentioning self-claim is an important quirk imo
> * missing one test for when `claim_issuer != issuer` (i.e. hit that if block)

Yeah good point - I've fixed up the comments and added some more unit tests

2020-08-27 01:30 UTC, holygits approved these changes
nice one

2020-08-27 02:07 UTC, merged