Chore/upstream merge
plugblockchain/plug-blockchain pull request #25
Opened 2019-11-13 23:41 UTC by holygits

Lot's of block synchronization fixes and internal refactors from upstream

2019-11-18 21:27 UTC, cowboy-bebug requested changes
Looks good! I think we just need to remove `README.adoc` and edit/delete `CONTRIBUTING.adoc` as well (it keeps popping up when making a PR)

2019-11-18 21:27 UTC, elim0322 commented on README.adoc
> += Substrate
Do we want to remove this file?

2019-11-18 21:46 UTC, alexsednz commented on node/primitives/src/lib.rs
> +pub type Signature = MsultiSignature;
Is this an expected change?

2019-11-18 21:48 UTC, alexsednz commented on srml/executive/tests/doughnut_integration.rs
> +#[allow(deprecated)] // Allow ValidateUnsigned
The comment is not expressive to me.

2019-11-18 21:50 UTC, alexsednz commented on node/primitives/src/lib.rs
> +pub type Signature = MsultiSignature;
Okay! I saw it was fixed in the following commit.

2019-11-18 21:54 UTC, aliXsed approved these changes

2019-11-19 01:46 UTC, cowboy-bebug approved these changes
Yep looks good!

2019-11-19 01:47 UTC, elim0322 commented
We might need to remove signing commits for this one 😄

2019-11-19 03:16 UTC, merged