Keep origin of contract call stack
plugblockchain/plug-blockchain pull request #38
Opened 2019-12-19 05:23 UTC by alexsednz

Closes #34

2019-12-19 05:25 UTC, alexsednz commented
@holygits This is my understanding of the task. Please correct me if I'm wrong.

2019-12-19 05:26 UTC, alexsednz commented
@holygits Also do we need to add some unit tests to check this?

2019-12-19 05:31 UTC, holygits commented
Yeah this is it. There should be tests for
- origin is correct at top level call
- origin is correct for nested call

2019-12-19 05:31 UTC, holygits commented on frame/contracts/src/exec.rs
> +			self_account: source_account,
I think `origin.clone()` would be clearer

2019-12-19 05:37 UTC, holygits commented on frame/contracts/src/exec.rs
> +	origin: T::AccountId, // origin has the same value as caller except for nested calls
Can be a doc comment: ```///  `origin` is the account which authored the original extrinsic leading to the current contract call(s). It does not change on nested calls as with `caller` ```

2019-12-19 20:24 UTC, alexsednz commented on frame/contracts/src/exec.rs
> +			self_account: source_account,
I wanted to call only one clone, but I agree origin.clone would be clearer.

2019-12-19 22:58 UTC, cowboy-bebug commented
For the build issue, we need to resolve this error:
```
   Compiling pallet-elections-phragmen v2.0.0 (/Users/ericlim/project/plug-blockchain-2/frame/elections-phragmen)
   Compiling sp-consensus-babe v2.0.0 (/Users/ericlim/project/plug-blockchain-2/primitives/consensus/babe)
   Compiling pallet-contracts v2.0.0 (/Users/ericlim/project/plug-blockchain-2/frame/contracts)
error[E0407]: method `origin` is not a member of trait `Ext`
   --> /Users/ericlim/project/plug-blockchain-2/frame/contracts/src/exec.rs:763:2
    |
763 |       fn origin(&self) -> &T::AccountId {
    |  _____^
764 | |         &self.origin
765 | |     }
    | |_____^ not a member of trait `Ext`
```

2019-12-19 23:12 UTC, cowboy-bebug requested changes
Nice and clean! Just need to add `fn origin()` to the `Ext` trait to resolve build issue:
https://github.com/plugblockchain/plug-blockchain/blob/0966e9d414e018f7a1ab85b6ed145eb78af590a6/frame/contracts/src/exec.rs#L96

2019-12-20 00:16 UTC, alexsednz commented
> Nice and clean! Just need to add `fn origin()` to the `Ext` trait to resolve build issue:
> https://github.com/plugblockchain/plug-blockchain/blob/0966e9d414e018f7a1ab85b6ed145eb78af590a6/frame/contracts/src/exec.rs#L96

Thank you Eric! I will do. I created the PR early even before building it as a draft PR to make sure I'm on the right track.

2019-12-20 03:19 UTC, alexsednz commented on frame/contracts/src/exec.rs
> +	origin: T::AccountId, // origin has the same value as caller except for nested calls
I added the doc to the public interface instead.

2019-12-22 22:14 UTC, cowboy-bebug requested changes
Looks good! I think we might want to add one more test for origin() like the tests below:
https://github.com/plugblockchain/plug-blockchain/blob/0966e9d414e018f7a1ab85b6ed145eb78af590a6/frame/contracts/src/wasm/mod.rs#L767
https://github.com/plugblockchain/plug-blockchain/blob/0966e9d414e018f7a1ab85b6ed145eb78af590a6/frame/contracts/src/wasm/mod.rs#L829

2019-12-23 03:23 UTC, cowboy-bebug approved these changes
Yep that's it! Nice work!! 👍

2019-12-23 19:59 UTC, merged