add optional doughnut parameter to contract calls
plugblockchain/plug-blockchain pull request #44
Opened 2020-01-06 23:54 UTC by cowboy-bebug

Changes:
- ExecutionContext has optional doughnut associated type
- added optional doughnut param to methods where needed
- for tests and node/runtime, None is used as doughnut for now

Closes #33

2020-01-08 20:49 UTC, jordy25519 requested changes
PR looks good in general
- Don't need `ext_doughnut` call to be implemented for this PR but left feedback anyway ;)
- Pass the doughnut by ref if possible (may require change to @alexsednz s work)

2020-01-08 20:49 UTC, holygits commented on frame/contracts/src/wasm/mod.rs
> +				(i32.const 0)
This is constant `0`, comment above says `1`

2020-01-08 20:49 UTC, holygits commented on frame/contracts/src/wasm/mod.rs
> +	/// calls `ext_doughnut`, loads the doughnut from the scratch buffer and
This test is only checking the return status code: it should assert the contents of the buffer aswell, like with this one: https://github.com/plugblockchain/plug-blockchain/blob/37c0fcfb34923ce5692932b76fe97b5f7cb68580/frame/contracts/src/wasm/mod.rs#L880-L895

2020-01-08 20:49 UTC, holygits commented on frame/contracts/src/wasm/runtime.rs
> +	ext_doughnut(ctx) -> u32 => {
We don't need this function to be implemented yet, if at all

2020-01-08 20:49 UTC, holygits commented on frame/contracts/src/exec.rs
> +	pub doughnut: Option<T::Doughnut>,
We should make this by ref if possible `Option<&T::Doughnut>` and avoid all the clones

2020-01-08 20:52 UTC, cowboy-bebug commented on frame/contracts/src/wasm/runtime.rs
> +	ext_doughnut(ctx) -> u32 => {
Thanks! I'll remove it and the related test 😄

2020-01-09 00:08 UTC, alexsednz commented on frame/contracts/src/exec.rs
> +	pub doughnut: Option<&'a T::Doughnut>,
Wouldn't it be better that we pass the doughnut in through RawOrigin::Signed(issuer, doughnut) as it is for RawOrigin::Delegated for the sake of consistency?

2020-01-09 00:11 UTC, cowboy-bebug commented on frame/contracts/src/exec.rs
> +	pub doughnut: Option<&'a T::Doughnut>,
Yeah I wasn't sure which doughnut to use so just used one from `system::Trait`

2020-01-09 00:14 UTC, alexsednz commented on frame/contracts/src/exec.rs
> +	pub doughnut: Option<&'a T::Doughnut>,
Yup, if we do so then we wouldn't have two doughnuts passed in directly and indirectly through RawOrigin.

2020-01-09 00:25 UTC, cowboy-bebug commented on frame/contracts/src/exec.rs
> +	pub doughnut: Option<&'a T::Doughnut>,
I see what u mean but they are the same thing as `system::Trait` is defined as:
```rust
pub trait Trait: 'static + Eq + Clone {
    /// The aggregated `Origin` type used by dispatchable calls.
    type Origin: Into<Result<RawOrigin<Self::AccountId, Self::Doughnut>, Self::Origin>> + 
    From<RawOrigin<Self::AccountId, Self::Doughnut>> +
    ...
}
```
`Self::Doughnut` is the `T::Doughnut`

2020-01-09 02:06 UTC, alexsednz commented on frame/contracts/src/exec.rs
> +	pub doughnut: Option<&'a T::Doughnut>,
That's why I suggest we should only have one of them. If they could be different then there could be scenarios why we would need to get either of these doughnuts separately and that could justify passing in two references. Does it make sense?

2020-01-11 01:57 UTC, cowboy-bebug commented on frame/contracts/src/exec.rs
> +	pub doughnut: Option<&'a T::Doughnut>,
It's more clear and consistent to me that we are using `system::Trait::Doughnut` type, similar to how RawOrigin and DelegatedDispatchVerifier are also using `system::Trait::Doughnut` type. And we are not passing anything just yet, it's just declaring what the type should be for the doughnut field.

2020-01-12 21:31 UTC, hoani approved these changes
LGTM

2020-01-12 21:32 UTC, jordy25519 requested changes
Looks good! Should add a couple integration tests to check `verify_contract_to_contract_call` works correctly. forgot to request this for `runtime_to_contract` in #47

2020-01-12 21:32 UTC, holygits commented on frame/contracts/src/wasm/runtime.rs
> +				&callee,
This one should be the `origin` address

2020-01-12 21:32 UTC, holygits commented on frame/contracts/src/wasm/runtime.rs
> +			type DelegatedDispatchVerifierOf<E> = <<E as Ext>::T as system::Trait>::DelegatedDispatchVerifier;
Can move the type alias to the top of the file

2020-01-14 02:12 UTC, jordy25519 approved these changes

2020-01-14 02:12 UTC, holygits commented
LGTM 🎉 🎉 🎉

2020-01-14 04:00 UTC, merged

2020-01-17 03:06 UTC, holygits commented on frame/contracts/src/lib.rs
> +			doughnut: Option<T::Doughnut>,
so `doughnut` should be extracted from the `origin`. the additional parameter here and in `instantiate` should be removed

2020-01-20 19:57 UTC, cowboy-bebug commented on frame/contracts/src/lib.rs
> +			doughnut: Option<T::Doughnut>,
Fixed by https://github.com/plugblockchain/plug-blockchain/pull/49