Contract to runtime call permissioning
plugblockchain/plug-blockchain pull request #48
Opened 2020-01-15 02:32 UTC by royyang-centrality

Added delegated runtime dispatch that supports doughnut

2020-01-16 00:29 UTC, jordy25519 requested changes
👍 Needs refactor so that there are two types of dispatches

2020-01-16 00:29 UTC, holygits commented on frame/contracts/src/wasm/runtime.rs
> +		match ctx.ext.doughnut() {
There should be both a `dispatch_call` and a `dispatch_delegated_call`.
The first means contract wants to do something for itself, the second means contract wants to do something for user (if doughnut permits).
At the moment user can change contract intended behaviour by passing a doughnut

2020-01-16 02:04 UTC, cowboy-bebug commented on frame/contracts/src/wasm/runtime.rs
> +		match ctx.ext.doughnut() {
Thanks for spotting this!

2020-01-16 03:21 UTC, cowboy-bebug commented on frame/contracts/src/wasm/runtime.rs
> +		match ctx.ext.doughnut() {
Are we introducing duplicated calls by doing this?

2020-01-16 05:55 UTC, cowboy-bebug commented on frame/contracts/src/wasm/runtime.rs
> +			let d = (*doughnut).clone();
I don't think we need to verify doughnut at this stage (or do we?) because it's verified at
- `ext_call()` (for contract-contract calls) and
- `Contract::call()` (for runtime-contract calls)

2020-01-16 18:09 UTC, holygits commented on frame/contracts/src/wasm/runtime.rs
> +			let d = (*doughnut).clone();
Correct, no verification to do here. This is a `contract-runtime` call, it will be seen like any ordinary extrinsic with a doughnut and will be verified in the targeted runtime method

2020-01-16 18:19 UTC, jordy25519 reviewed
Add an integration test and then we're good 🍩

2020-01-16 18:19 UTC, holygits commented on frame/contracts/src/wasm/runtime.rs
> +	ext_delegated_dispatch_call(ctx, call_ptr: u32, call_len: u32) => {
This is it 👍. Could use a doc comment

2020-01-20 23:38 UTC, cowboy-bebug commented
I can't trigger `verify_contract_to_contract_call` to return error anymore because `Contract::call` checks for `verify_runtime_to_contract` first before actual contract call 😞

2020-01-21 20:41 UTC, holygits commented on frame/contracts/src/doughnut_integration.rs
> +	runtime_verifiable: bool,
Can doc comment these for the next guy 😉

2020-01-21 20:42 UTC, holygits commented on frame/contracts/src/doughnut_integration.rs
> +	let verifiable_doughnut = MockDoughnut::new(true, true);
Could builder pattern this but not important

2020-01-21 21:13 UTC, jordy25519 requested changes
Few clean ups, otherwise keen to merge this ASAP

2020-01-21 21:13 UTC, jordy25519 commented on frame/contracts/src/doughnut_integration.rs
> +fn delegated_contract_to_runtime_call_returns_error_with_unverifiable_doughnut() {
Name of this test is wrong as this is a test for `verify_runtime_to_contract_call`

2020-01-21 21:13 UTC, jordy25519 commented on frame/contracts/src/wasm/mod.rs
> +	fn delegated_dispatch_call_works_with_doughnut() {
Can add another test for when the doughnut is `None` here, it should error

2020-01-21 21:13 UTC, holygits commented on frame/contracts/src/doughnut_integration.rs
> +		assert_ok!(Contract::put_code(Origin::signed(ALICE), 100_000, wasm));
I notice some other tests are using `delegated_origin` to `put_code` can you fix them to use Alice like this one (I guess it was left over from when instantiate needed a Option<Doughnut>`

2020-01-21 21:40 UTC, cowboy-bebug commented on frame/contracts/src/doughnut_integration.rs
> +	let verifiable_doughnut = MockDoughnut::new(true, true);
Thanks for this comment! It's very clear how it's constructed now! should follow this pattern as much as possible 😄

2020-01-21 21:44 UTC, cowboy-bebug commented on frame/contracts/src/doughnut_integration.rs
> +fn delegated_contract_to_runtime_call_returns_error_with_unverifiable_doughnut() {
renaming to `delegated_runtime_to_contract_call_returns_error_with_unverifiable_doughnut`

2020-01-21 21:52 UTC, cowboy-bebug commented on frame/contracts/src/wasm/mod.rs
> +	fn delegated_dispatch_call_works_with_doughnut() {
`delegated_dispatch_call_fails_without_doughnut` is added

2020-01-21 23:12 UTC, holygits commented on frame/contracts/src/doughnut_integration.rs
> +		.set_runtime_verifiable(true)
Too good 🔥

2020-01-21 23:14 UTC, jordy25519 approved these changes
🚀 Looks good!

2020-01-21 23:45 UTC, merged