Decouple gas handling from gas payment
plugblockchain/plug-blockchain pull request #54
Opened 2020-01-24 02:57 UTC by alexsednz

Closes #53 
Create a separate trait for gas handling so we can customize its behaviour in the case of multi-currency gas payment in which we don't want the user to be charged upfront.

2020-01-24 05:33 UTC, jordy25519 requested changes
Yeah this looks good 👍 
We need to tidy up the imbalance that is being returned and passed around
It should be made into an `Option` since generating an imbalance is optional (only happens if we mint or burn currency) but there are two ways we could implement it
1) Make `fill_gas` return `Option<NegativeImbalance>` and `return_unused_gas` receive `Option<NegativeImbalance>`
**OR**
2) Make `imbalance` into a field on the gas meter itself so this imbalance "state" does not need to be passed around which seems cleaner. It should still be an `Option<NegativeImbalance>` though, maybe named like `pending_imbalance`

Last note would be `GasHandling` -> `GasHandler` to fit the naming convention

2020-01-24 05:33 UTC, holygits commented on frame/contracts/src/gas.rs
> +	fn fill_gas(transactor: &T::AccountId, gas_limit: Gas) -> Result<(GasMeter<T>, NegativeImbalanceOf<T>), &'static str>
The imbalance result from `fill_gas` should be made into an `Option` as it implies some imbalance was generated (which may not be the case).

The `imbalance` parameter for `return_unused_gas` should also be an `Option` as it seems to be used as a way to pass the imbalance from the buy step into the refund step.

Passing the imbalance, instead of dropping immediately, appears to be an optimization.
If it was not passed between the methods then there would be two updates to the currency's issuance. One when gas is bought (negative imbalance) and another when gas is refunded (positive imbalance).
At the moment the two get merged into one when the `imbalance.offset(refund)` is called. This means there is only one update to the currency's issuance, instead of two.

2020-01-27 21:23 UTC, hoani commented on frame/contracts/src/gas.rs
> +	fn return_unused_gas(
Because we don't require that gas is actually returned here, I suggest naming this `handle_unused_gas`

2020-01-27 21:24 UTC, hoani commented on frame/contracts/src/gas.rs
> +	fn fill_gas(transactor: &T::AccountId, gas_limit: Gas) -> Result<(GasMeter<T>, NegativeImbalanceOf<T>), &'static str>
Are we sure we want to include imbalance logic in the contracts module?
I think gas belongs here, but imbalance logic is currency specific

2020-01-27 21:28 UTC, hoani commented on frame/contracts/src/gas.rs
> +	fn return_unused_gas(
^ looking at the description, `empty_remaining_gas` is a good name too

2020-01-27 22:05 UTC, holygits commented on frame/contracts/src/gas.rs
> +	fn fill_gas(transactor: &T::AccountId, gas_limit: Gas) -> Result<(GasMeter<T>, NegativeImbalanceOf<T>), &'static str>
The imbalance logic is already tied into the contracts module for other currency related stuff. We could remove it from the "gas" part of the module, but removing from the whole thing is a much larger issuer

2020-01-27 23:20 UTC, cowboy-bebug commented on frame/contracts/src/gas.rs
> +	fn fill_gas(transactor: &T::AccountId, gas_limit: Gas) -> Result<(GasMeter<T>, NegativeImbalanceOf<T>), &'static str>
Instead of changing the return type to be Option, can we do something like this in GasHandling::buy_gas():
```rust
buy_gas::<T>(transactor, gas_limit)
	.map(|(gas_meter, imbalance)|) {
		if imbalance.is_zero() {
			(gas_meter, 0.into())
		}
	})
```
And propagate 0 imbalance throughout execute_wasm() and put_code()

2020-01-28 02:23 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +	fn fill_gas(transactor: &T::AccountId, gas_limit: Gas) -> Result<(GasMeter<T>, NegativeImbalanceOf<T>), &'static str>
@royyang-centrality @hoani and I discussed different options and decided to get rid of this coupling altogether. As @holygits pointed out passing imbalance was introduced as an optimization measure so during a contract execution they call on_unbalance only once after refunding. This trivial optimization would cost us an ugly coupling between gas payment and gas handling if we insist to keep it. The alternative solution that we have taken is we settle any imbalance whenever it is incurred at its own time. So a payment or a deposit will deal with imbalance internally and appear complete to outside.

2020-01-28 02:43 UTC, holygits commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
can we just use `refund_imbalance`, without offset?

2020-01-28 02:44 UTC, holygits commented on frame/contracts/src/lib.rs
> +	type GasHandler: GasHandler<Self>;
Add a doc comnent 😄

2020-01-28 02:45 UTC, holygits commented on frame/contracts/src/gas.rs
> +	fn fill_gas(transactor: &T::AccountId, gas_limit: Gas) -> Result<(GasMeter<T>, NegativeImbalanceOf<T>), &'static str>
Much cleaner now. I think the point of the optimization was so that there would only be one write to storage

2020-01-28 20:39 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
No. refund_imbalance is PositiveImbalance and on_unbalanced takes NegativeImbalance.

2020-01-28 21:17 UTC, holygits commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
Ok so is this code passing the refund as a negative imbalance? it should just be zero negative imbalance if that is the case

2020-01-28 21:19 UTC, holygits commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
Actually, I think we can remove this altogether, as it was intended to drop the "net" negative imbalance across buy and refund steps. But we already drop the negative imbalance in buy step now

2020-01-28 21:22 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
Would you please elaborate on your point a bit? Previously we would pass
`neg_imb - pos_imb`
Now because we have settled "neg_imb" at the payment site, so here neg_imb is zero. That means we should pass:
`zero - pos_imb`

2020-01-28 21:28 UTC, holygits commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
Won't this create a negative imbalance? `zero - pos_imb`

2020-01-28 21:28 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
Even if on_unbalance is going to ignore what we are passing in the second step, I would say let's keep it, so in any possible future changes we could keep accounting simple by maintaining symmetry.

2020-01-28 21:32 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
What I know about `zero - pos_imb` is that it's consistent with the previous logic here.

2020-01-28 21:36 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
By reading the code I guess it would result in Err and thus will be ignored

2020-01-28 21:38 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
Anyway, if you think the logic of settling imbalance would not change substantially, removing it altogether seems not to be wrong.

2020-01-28 22:01 UTC, holygits commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
I think this will always be a noop. refuned will be 0 or positive, if its 0 it will make another 0, if its positive it will make a `Err<PositiveImbalance>` and miss the let binding. SO makes sense to remove, since this code was here based on the assumption a "net" negative imbalance would be passed in

2020-01-28 22:19 UTC, HaoZhaiX commented on frame/contracts/src/gas.rs
> +	fn fill_gas(transactor: &T::AccountId, gas_limit: Gas) -> Result<GasMeter<T>, &'static str>
Awesome work!  A small case I would recommend is to add associated `type Error` instead use `&'static str` directly, something like this: `type Error: From<Error> + std::fmt::Debug + 'static;` , For example: it would be more flexible if we want to support multi errors with Enum

2020-01-28 22:37 UTC, cowboy-bebug commented on frame/contracts/src/gas.rs
> +	fn fill_gas(transactor: &T::AccountId, gas_limit: Gas) -> Result<GasMeter<T>, &'static str>
I think all `Result<(), &'static str>` changed to `Result<(), DispatchError>` or `DispatchResult` in the latest merge as well

2020-01-28 22:46 UTC, cowboy-bebug commented on frame/contracts/src/gas.rs
> +	if let Ok(imbalance) = NegativeImbalanceOf::<T>::zero().offset(refund_imbalance) {
Yep `deposit_creating()` always returns +ve or zero PositiveImbalance

2020-01-28 22:59 UTC, HaoZhaiX commented on frame/contracts/src/gas.rs
> +	fn fill_gas(transactor: &T::AccountId, gas_limit: Gas) -> Result<GasMeter<T>, &'static str>
You are right https://github.com/plugblockchain/plug-blockchain/blob/55aa532059755cc37141949fc6f428a305b07c44/primitives/runtime/src/lib.rs#L359  Using `Result<(), DispatchError>` or `DispatchResult` would be the best practice for now

2020-01-28 23:11 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +	fn fill_gas(transactor: &T::AccountId, gas_limit: Gas) -> Result<GasMeter<T>, &'static str>
Done

2020-01-28 23:35 UTC, jordy25519 approved these changes
Very clean now, nice job! LGTM (pending CI passes and an integration test, could be in follow up PR)

2020-01-29 00:15 UTC, cowboy-bebug requested changes
Yep looks good! 🎉 
I got minor changes requested around comments. And if you'd like `NegativeImbalanceOf` import in gas.rs could be removed as we don't use it anymore.

Also a reminder to rebase to the latest develop and update `CHANGELOG.md` with things that this PR brings in 😄

2020-01-29 00:15 UTC, cowboy-bebug commented on frame/contracts/src/lib.rs
> -		// paying for the gas.
Could we keep this comment (for the next person who works on this bit of code). Something like this:
```rust
// Fill up the gas meter upfront. Default behaviour is to pay for the gas upfront.
//
// NOTE: it is very important to avoid any state changes before
// paying for the gas.
```

2020-01-29 00:15 UTC, cowboy-bebug commented on frame/contracts/src/lib.rs
> -		// can alter the balance of the caller.
Can we also keep this comment and modify it to apply to our change:
```rust
// Handle unused gas. Default behaviour is to refund cost of the unused gas.
//
// NOTE: This should go after the commit to the storage, since the storage changes
// can alter the balance of the caller.
```

2020-01-29 00:15 UTC, cowboy-bebug commented on frame/contracts/src/lib.rs
> +	/// Handler for filling and emptying the gas tank for a contract.
`/// Handler for filling and emptying the gas meter for a contract.` <- just to avoid any confusion

2020-01-29 00:15 UTC, cowboy-bebug commented on frame/contracts/src/gas.rs
>  	let refund_imbalance = T::Currency::deposit_creating(transactor, refund);
Can we make it `_refund_imbalance` to avoid `unused_variables` warning

2020-01-29 00:19 UTC, alexsednz commented on frame/contracts/src/lib.rs
> +	/// Handler for filling and emptying the gas tank for a contract.
Meter is a gauge counting your consumption. So technically we don't fill the meter.

2020-01-29 00:25 UTC, alexsednz commented on frame/contracts/src/lib.rs
> -		// paying for the gas.
I am not very pro implementation comments unless you are doing something that may look wrong or has hidden implications. Ideally, It's your code that should be readable. In this case, "we are filling the gas, which is not hard to see"

2020-01-29 00:26 UTC, alexsednz commented on frame/contracts/src/lib.rs
> -		// can alter the balance of the caller.
Similarly in this case. We, instead, have added nice documentation comments to the trait explaining what we do.

2020-01-29 00:28 UTC, cowboy-bebug commented on frame/contracts/src/lib.rs
> +	/// Handler for filling and emptying the gas tank for a contract.
We do fill and empty the meter according to `GasHandler` doc comments

2020-01-29 00:50 UTC, alexsednz commented on frame/contracts/src/lib.rs
> +	/// Handler for filling and emptying the gas tank for a contract.
Yeah, you are right. That comment is from @royyang-centrality. On a second look, I'd say it's GasMeter that I would rather be called GasTank. But I don't see that much value in refactoring it. So alright. I will change the comment here.

2020-01-29 20:56 UTC, HaoZhaiX commented on frame/contracts/src/lib.rs
> -		// paying for the gas.
For me, I prfer to keep this comment

2020-01-29 20:56 UTC, mzxyz approved these changes

2020-01-29 21:45 UTC, cowboy-bebug approved these changes

2020-01-29 21:59 UTC, hoani approved these changes

2020-01-29 22:12 UTC, merged