Uncouple emptying gas_meter from updating the gas spent for the block
plugblockchain/plug-blockchain pull request #68
Opened 2020-02-24 00:40 UTC by alexsednz

Closes #67

2020-02-24 01:32 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +		Self::empty_unused_gas(transactor, gas_meter);
I'm uncertain whether this would actually call the overridden function in the places that we have implemented this trait. I will do a test soon.

2020-02-24 02:49 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +		Self::empty_unused_gas(transactor, gas_meter);
My test showed this should work. So we can go ahead.

2020-02-24 03:44 UTC, cowboy-bebug commented on frame/contracts/src/gas.rs
> -
Do we need to call the update method here to ensure the default behaviour here (please ignore me if we don't need to)?
```rust
Self::update(transactor, gas_meter);
```

2020-02-24 04:18 UTC, cowboy-bebug commented
I think the build errors are coming from the way we use the latest nightly in our circleci config. Let me fix it in another PR

2020-02-24 04:31 UTC, holygits commented
related: https://github.com/rustwasm/wasm-bindgen/issues/2009

2020-02-24 04:33 UTC, holygits commented on frame/contracts/src/gas.rs
> +		Self::empty_unused_gas(transactor, gas_meter);
Can you add a specific unit test to see a custom impl updates gas_spent

2020-02-24 04:42 UTC, holygits commented on frame/contracts/src/gas.rs
> +	fn update(transactor: &T::AccountId, gas_meter: GasMeter<T>) {
a more specific name would be good here

2020-02-24 21:01 UTC, alexsednz commented on frame/contracts/src/gas.rs
> -
It's now the other way around. The update method's default is to call this function. So the default behaviour would remain as it was before.

2020-02-24 23:34 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +		Self::empty_unused_gas(transactor, gas_meter);
I made a change so customized_fill_gas_does_not_charge_the_user, if passed, would prove the right empty_unused_gas is called.

2020-02-24 23:34 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +	fn update(transactor: &T::AccountId, gas_meter: GasMeter<T>) {
Done.

2020-02-25 02:19 UTC, hoani commented on frame/contracts/src/gas.rs
> +	fn finish(transactor: &T::AccountId, gas_meter: GasMeter<T>) {
I don't think that `finish` is more descriptive than `update`, but I will let @holygits decide since it was his concern in the first place.

2020-02-25 02:36 UTC, hoani requested changes
Please see requested changes, happy to discuss design decisions =)

2020-02-25 02:36 UTC, hoani commented on frame/contracts/src/gas.rs
> +		GasSpent::mutate(|block_gas_spent| *block_gas_spent += gas_meter.spent());
From my understanding, we want to separate contract logic from gas handler logic.
The reason is so that anyone who implements a gas handler can choose how to pay for gas, but we don't want that user to determine how a contract tracks gas spent.
If we put `finish` in the `GasHandler`, then the user still decides how the contract tracks gas.

In my opinion, to follow these rules, we should insert:
`GasSpent::mutate(|block_gas_spent| *block_gas_spent += gas_meter.spent());`
On line 592 (https://github.com/plugblockchain/plug-blockchain/blob/613e545f8ac6f07abdf8eacd7457c18fece6f0af/frame/contracts/src/lib.rs#L592)
and line 760 (https://github.com/plugblockchain/plug-blockchain/blob/613e545f8ac6f07abdf8eacd7457c18fece6f0af/frame/contracts/src/lib.rs#L760)
of the Contracts `lib.rs` so that full control is under the contract for how it tracks gas spent

2020-02-25 02:45 UTC, holygits commented on frame/contracts/src/gas.rs
> +		GasSpent::mutate(|block_gas_spent| *block_gas_spent += gas_meter.spent());
We could do some kind of decorator but this would be so much simpler XD

2020-02-25 03:01 UTC, alexsednz commented on frame/contracts/src/gas.rs
> +		GasSpent::mutate(|block_gas_spent| *block_gas_spent += gas_meter.spent());
The logic that updates the gas spent for the block is still relevant to the gas handler. The fact is a gas meter has two data. The gas spent that should be used to update the gas spent for the block and the gas left which is used in emptying unused gas. It seemed relevant to me to bundle these two into a function that would be used before finishing a contract as we would never want for one of these two to happen without the other one. 
On the other hand, the real aim was, we wanted to make sure if "empty_unused_gas" is overridden, the gas spent for the block would still keep being updated without exposing any new gas specific function of Plug to other projects like cennznet.

2020-02-25 23:29 UTC, jordy25519 approved these changes
TY LGTM

2020-02-26 01:16 UTC, hoani approved these changes
LGTM 👍

2020-02-26 01:32 UTC, cowboy-bebug approved these changes
LGTM !

2020-02-26 01:40 UTC, merged