Chore/162 improve imbalance
plugblockchain/plug-blockchain pull request #77
Opened 2020-03-30 20:41 UTC by HaoZhaiX

This pr try to improve the Positive/NegativeImbalance so they are fully compatible with our Generic Asset module

## Changes
- Check asset_id consistency in `merge`, `subsume` and `offset` functions for both `NegativeImbalance` and `NegativeImbalance`

## Tests
- If imBalance is initialised by `zero` function, asset_id should be updated when calling `merge`, `subsume` or `offset` function.
- Should panic under debug env if asset_id is not consistency when calling `merge`, `subsume` or `offset` function.
- `total_issuance` should be updated after imBalance dropped.

2020-03-30 23:42 UTC, hoani commented on frame/generic-asset/src/lib.rs
> +	/// Trait used to avoid duplicate code that is implemented for both the Positive and Negative
I would remove the first two lines of these comments - the third line describes the purpose of this trait really nicely 😄

2020-03-30 23:44 UTC, hoani commented on frame/generic-asset/src/lib.rs
> +			if self.asset_id() != other.asset_id() {
[suggestion] tempted to just go `return self.asset_id() == other.asset_id()`, it depends on how much we want the `debug_asset!`

2020-03-30 23:48 UTC, hoani commented on frame/generic-asset/src/lib.rs
> +			if asset_id != other.1 {
Shouldn't we be using `self.match_asset_id(&other)` here?
Then we can just use `self.1` instead of `asset_id` below

2020-03-30 23:49 UTC, hoani commented on frame/generic-asset/src/lib.rs
> +			if asset_id != other.1 {
^ Same comment as above

2020-03-30 23:50 UTC, hoani commented on frame/generic-asset/src/tests.rs
> +			let mut negative_im = NegativeImbalanceOf::zero();
[nitpick] can remove `mut` here

2020-03-30 23:52 UTC, hoani commented on frame/generic-asset/src/tests.rs
> +fn negative_imbalance_merge_with_imcompatible_asset_id_should_panic() {
Suggest naming these to `..._should_error` we don't want to panic ;)

2020-03-30 23:53 UTC, hoani commented on frame/generic-asset/src/tests.rs
> +		let _ = negative_im.merge(other);
did we miss an `assert_err()` here?

2020-03-30 23:54 UTC, hoani commented on frame/generic-asset/src/tests.rs
> +	});
Very nice 👍

2020-03-30 23:58 UTC, hoani commented on frame/generic-asset/src/tests.rs
> +fn zero_asset_id_should_updated_after_negative_imbalance_operations() {
We are currently covering the cases:
* `asset_id(A) = 0, asset_id(B) = 16000`
I think it would be good to add the cases 
* `asset_id(A) = 16000, asset_id(B) = 16000`
This could be done by merging, subsuming and offsetting twice in this test

2020-03-30 23:59 UTC, hoani requested changes
Great work so far @HaoZhaiX @royyang-centrality 
I have added some comments for you to consider, overall the design and test coverage is great

2020-03-31 00:08 UTC, royyang-centrality commented on frame/generic-asset/src/lib.rs
> +	/// Trait used to avoid duplicate code that is implemented for both the Positive and Negative
Got it

2020-03-31 00:09 UTC, royyang-centrality commented on frame/generic-asset/src/lib.rs
> +			if self.asset_id() != other.asset_id() {
I think it's important to assert because operating on imbalances with different asset ID definitely indicate bugs I the code and we should catch it early

2020-03-31 00:16 UTC, royyang-centrality commented on frame/generic-asset/src/lib.rs
> +			if asset_id != other.1 {
We can't - the "self" is not passed in as a mutable reference so we can't change the asset id.
In addition there's no point because the code  "forget" both the "self" and "other" and construct a "new" imbalance to be returned.

2020-03-31 00:18 UTC, hoani commented on frame/generic-asset/src/lib.rs
> +			if self.asset_id() != other.asset_id() {
Fair enough, I'm happy either way 😄

2020-03-31 00:20 UTC, hoani commented on frame/generic-asset/src/lib.rs
> +			if asset_id != other.1 {
Good point 👍

2020-03-31 00:22 UTC, hoani commented on frame/generic-asset/src/tests.rs
> +fn negative_imbalance_merge_with_imcompatible_asset_id_should_panic() {
Resolving this - turns out we might be ok with panicking

2020-03-31 00:30 UTC, royyang-centrality commented on frame/generic-asset/src/tests.rs
> +fn negative_imbalance_merge_with_imcompatible_asset_id_should_panic() {
currently the wrong asset_id will cause a debug_panic - we will panic to indicate a important bug, but only in debug environment

2020-03-31 00:54 UTC, HaoZhaiX commented on frame/generic-asset/src/tests.rs
> +fn negative_imbalance_merge_with_imcompatible_asset_id_should_panic() {
Good suggestion, just comparing to other test code which using `should_panic`, will change it to `should_failed`

2020-03-31 01:42 UTC, HaoZhaiX commented on frame/generic-asset/src/tests.rs
> +fn zero_asset_id_should_updated_after_negative_imbalance_operations() {
Good point, add check for imbalance operations with same asset id

2020-03-31 03:18 UTC, hoani approved these changes
Nice updates, LGTM

2020-03-31 19:40 UTC, cowboy-bebug approved these changes
LGTM! I have just one comment which could be addressed in another PR

2020-03-31 19:40 UTC, cowboy-bebug commented on frame/generic-asset/src/lib.rs
> +			if self.get_asset_id() == Zero::zero() {
I think it's possible to create an asset with `asset_id = 0`, which will be replaced by `other`. It might be worthwhile to disallow creating an asset with id = 0.

2020-03-31 20:14 UTC, HaoZhaiX commented on frame/generic-asset/src/lib.rs
> +			if self.get_asset_id() == Zero::zero() {
Yes, we could let `Next_Asset_id` not start from `zero`

2020-03-31 21:17 UTC, hoani commented on frame/generic-asset/src/lib.rs
> +			if self.get_asset_id() == Zero::zero() {
We will also need to make sure `asset_id` can not be 0 in `fn create_reserved`

2020-03-31 22:05 UTC, merged

2020-03-31 22:11 UTC, royyang-centrality commented on frame/generic-asset/src/lib.rs
> +			if self.get_asset_id() == Zero::zero() {
jira created here: 
https://centralitydev.atlassian.net/browse/BT-184